# File: .github/workflows/testNginxForAzureDeploy.yml

name: Test Github action to update NGINX for Azure configurations
on:
  schedule:
    - cron:  '0 20 * * *'

env:
  NGINX_DEPLOYMENT_NAME: githhubci-test-dep
  NGINX_CONFIG_FILE: test/configs/nginx.conf
  TEST_RESOURCE_GROUP_NAME: testenv-0da38993-workload

permissions:
  id-token: write
  contents: read

jobs:
  Update-NGINX-Configuration:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v2
    - name: 'Update config'
      shell: bash
      run: |
        sed -i 's/000000/'"$GITHUB_RUN_ID"'/g' $NGINX_CONFIG_FILE
    - name: 'AZ CLI Login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: 'Sync NGINX configuration to NGINX on Azure instance'
      uses: nginxinc/nginx-for-azure-deploy-action@v0
      with:
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resource-group-name: $TEST_RESOURCE_GROUP_NAME
        nginx-deployment-name: $NGINX_DEPLOYMENT_NAME
        nginx-config-relative-file-path: $NGINX_CONFIG_FILE
    - name: 'Validate config update'
      shell: bash
      run: |
        wget -O - -o /dev/null http://${{ secrets.NGINX_DEPLOYMENT_IP }} | jq '.request.headers."Github-Run-Id"  | test( "'"$GITHUB_RUN_ID"'")'
